### PR TITLE
Included tests for pkg/assembler/helper

### PR DESCRIPTION
**Pull request by nathannaveen**
- Included tests for `pkg/assembler/helper`
- 100% coverage

Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

### CODE REVIEW

**Comment by pxp928** [comment]
Thanks @nathannaveen! Looks like the static analysis is failing on the order of the `imports`:
```
import (
	"reflect"
	"testing"

	"github.com/guacsec/guac/pkg/handler/processor"
)
```
fixes that check error.

**Review by pxp928 — CHANGES_REQUESTED** [review]
Thanks @nathannaveen! Looks like the static analysis is failing on the order of the imports:
```
import (
	"reflect"
	"testing"

	"github.com/guacsec/guac/pkg/handler/processor"
)
```
fixes that check error.

**Review by pxp928 — APPROVED** [review]
LGTM!

**Review by lumjjb — APPROVED** [review]
LGTM! Thank you so much for your PR @nathannaveen !!! Welcome!

**Pull request merged**
