### PR TITLE
Removed Empty String Parents for Root Nodes

### LINKED ISSUE #1120: [bug] pkg/guacanalytics/patchPlanning.go fills in parent field for root nodes
**Describe the bug**
pkg/guacanalytics/patchPlanning.go for the root/input nodes which should have an empty parents list, the program for some reason populated this field to contain an empty string.

**To Reproduce**

1. Run the SearchDependenciesFromStartNode func
2.  Run ToposortFromBfsNodeMap on the output (pkg/guacanalytics/toposort.go)
3. You will notice it doesn't enter the len(parentsList) == 0, even for the root nodes that do not have a parent so it thinks a cycle is detected
4. Try adding "parentsList[0] == "" && len(parentsList) == 1" to the if statement and you will see it does enter the clause

**Expected behavior**
len(parentsList) should == 1 for the start nodes inputted

### PR DESCRIPTION
**Pull request by nathannaveen**
# Description of the PR

* In pkg/guacanalytics/patchPlanning.go removed the empty string parents for root nodes. The explanation for this is: https://github.com/guacsec/guac/issues/1120#issuecomment-1667069470
* Changed q.now to a pointer
* Fixes #1120

# PR Checklist

- [ ] All commits have [a Developer Certificate of Origin (DCO)](https://wiki.linuxfoundation.org/dco) -- they are generated using `-s` flag to `git commit`.
- [ ] All new changes are covered by tests
- [ ] If GraphQL schema is changed, `make generate` has been run
- [ ] If `collectsub` protobuf has been changed, `make proto` has been run
- [ ] All CI checks are passing (tests and formatting)
- [ ] All dependent PRs have already been merged

### CODE REVIEW

**Comment by rmetzman** [comment]
@nathannaveen try running "go test" on the pkg/guacanalytics directory.  I think something is causing the tests to fail according to the pre-submits.

**Comment by nathannaveen** [comment]
> @nathannaveen try running "go test" on the pkg/guacanalytics directory. I think something is causing the tests to fail according to the pre-submits.

I got it to work now, Thanks!

**Comment by rmetzman** [comment]
Hi Nathan-- I merged a PR #1129 with some edits in the same files so I think this PR (and maybe a few of your others on these same files) require a rebase.

**Comment by nathannaveen** [comment]
> Hi Nathan-- I merged a PR #1129 with some edits in the same files so I think this PR (and maybe a few of your others on these same files) require a rebase.

Resolved the conflicts, Thanks!

**Comment by pxp928** [comment]
@rmetzman did you want to re-review this?

**Review by rmetzman — COMMENTED** [review]
Thanks for the fix!  LGTM

**Comment by nathannaveen** [comment]
@pxp928 A friendly reminder!

**Review by pxp928 — APPROVED** [review]
LGTM

**Review by lumjjb — APPROVED** [review]

**Pull request merged**
