### PR TITLE
[Neo4j] Added HashEqual neo4j backend implementation 

### PR DESCRIPTION
**Pull request by pxp928**
Signed-off-by: pxp928 <parth.psu@gmail.com>

Depends on #492

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]
LGTM, though I'd move the query building outside of the transaction

**Comment by pxp928** [comment]
Yes will do. Also fixing up another issue with nodes and edge. Hold off on this.

**Comment by pxp928** [comment]
Ready for review

**Review by mihaimaruseac — APPROVED** [review]

**Review by lumjjb — APPROVED** [review]
lgtm

**Pull request merged**
