### PR TITLE
Grab read mutex on Path and Neighbors.

### LINKED ISSUE #672: Backend concurrency panic
Looks like with #645 the nodes were done but not the path() and neighbors() queries.

```
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*demoClient).buildPackageResponse(0xc0002a24e0, 0x2?, 0x0)
	/home/jeffm/git/guac/pkg/assembler/backends/inmem/pkg.go:509 +0x58e
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*demoClient).convOccurrence(0xb46860?, 0xc000f43480)
	/home/jeffm/git/guac/pkg/assembler/backends/inmem/isOccurrence.go:186 +0x249
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*isOccurrenceStruct).BuildModelNode(0xb463e0?, 0xc0003b6000?)
	/home/jeffm/git/guac/pkg/assembler/backends/inmem/isOccurrence.go:57 +0x25
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*demoClient).buildModelNodes(0xc0002a24e0, {0xc00003ca10, 0x1c, 0xc00001eed8?})
	/home/jeffm/git/guac/pkg/assembler/backends/inmem/path.go:68 +0x9b
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*demoClient).Neighbors(0xc00001ef01?, {0xc00001eef8?, 0xa9bc05?}, {0xc002799030?, 0xc0012d1b00?})
```

<details>
  <summary> full stack trace </summary>

```
fatal error: concurrent map read and map write

goroutine 273010 [running]:
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*demoClient).buildPackageResponse(0xc0002a24e0, 0x2?, 0x0)
	/home/jeffm/git/guac/pkg/assembler/backends/inmem/pkg.go:509 +0x58e
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*demoClient).convOccurrence(0xb46860?, 0xc000f43480)
	/home/jeffm/git/guac/pkg/assembler/backends/inmem/isOccurrence.go:186 +0x249
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*isOccurrenceStruct).BuildModelNode(0xb463e0?, 0xc0003b6000?)
	/home/jeffm/git/guac/pkg/assembler/backends/inmem/isOccurrence.go:57 +0x25
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*demoClient).buildModelNodes(0xc0002a24e0, {0xc00003ca10, 0x1c, 0xc00001eed8?})
	/home/jeffm/git/guac/pkg/assembler/backends/inmem/path.go:68 +0x9b
github.com/guacsec/guac/pkg/assembler/backends/inmem.(*demoClient).Neighbors(0xc00001ef01?, {0xc00001eef8?, 0xa9bc05?}, {0xc002799030?, 0xc0012d1b00?})
	/home/jeffm/git/guac/pkg/assembler/backends/inmem/path.go:55 +0x72
github.com/guacsec/guac/pkg/assembler/graphql/resolvers.(*queryResolver).Neighbors(0xb343e0?, {0xd28680?, 0xc002f3ef60?}, {0xc002799030?, 0xc000100000?})
	/home/jeffm/git/guac/pkg/assembler/graphql/resolvers/path.resolvers.go:20 +0x38
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query_neighbors.func2({0xd28680?, 0xc002f3ef60})
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/artifact.generated.go:3751 +0xcc
github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0xd28680?, 0xc002f3ef60?}, 0xc003def570?)
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/executor/extensions.go:72 +0x26
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query_neighbors(0xc000c0c6c0, {0xd28680, 0xc002f3ee70}, {0xc000b30500?, {0xc003de1600?, 0x4?, 0xc0044b3140?}})
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/artifact.generated.go:3749 +0x243
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func58({0xd28680?, 0xc002f3ee70?})
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/artifact.generated.go:4869 +0xae
github.com/99designs/gqlgen/graphql/executor.processExtensions.func3({0xd28680?, 0xc002f3ee70?}, 0xc000c0ca90?)
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/executor/extensions.go:69 +0x26
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func59({0xd28680?, 0xc002f3ee70?})
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/artifact.generated.go:4877 +0x32
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query.func60()
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/artifact.generated.go:4881 +0x25
github.com/99designs/gqlgen/graphql.(*FieldSet).Dispatch(0xc004d4ba40)
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/fieldset.go:34 +0x96
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Query(0xc000c0c6c0, {0xd28680, 0xc002f3ede0}, {0xc0020ae210, 0x1, 0x1})
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/artifact.generated.go:4945 +0x270
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executableSchema).Exec.func1({0xd28680?, 0xc002f3edb0?})
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/root_.generated.go:1905 +0x93
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1({0xd28680, 0xc002f3edb0})
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/executor/executor.go:119 +0x2b
github.com/99designs/gqlgen/graphql/executor.processExtensions.func2({0xd28680?, 0xc002f3edb0?}, 0xb00d40?)
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/executor/extensions.go:66 +0x26
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1({0xd28680, 0xc002f3ecf0})
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/executor/executor.go:118 +0x113
github.com/99designs/gqlgen/graphql/handler/transport.POST.Do({}, {0xd27eb0?, 0xc0058d8e00}, 0xc003dc7200, {0xd26f20, 0xc0002d1900})
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/handler/transport/http_post.go:87 +0x59f
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc0002ad4a0, {0xd27eb0, 0xc0058d8e00}, 0xc003dc7200)
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/handler/server.go:121 +0x212
net/http.(*ServeMux).ServeHTTP(0x0?, {0xd27eb0, 0xc0058d8e00}, 0xc003dc7100)
	/usr/lib/golang/src/net/http/server.go:2487 +0x149
net/http.serverHandler.ServeHTTP({0xd25c78?}, {0xd27eb0, 0xc0058d8e00}, 0xc003dc7100)
	/usr/lib/golang/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0002d0000, {0xd28680, 0xc0003b62d0})
	/usr/lib/golang/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:3102 +0x4db

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f84b53dc9d8, 0x72)
	/usr/lib/golang/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc0002a9780?, 0x6?, 0x0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc0002a9780)
	/usr/lib/golang/src/internal/poll/fd_unix.go:614 +0x234
net.(*netFD).accept(0xc0002a9780)
	/usr/lib/golang/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc000290138)
	/usr/lib/golang/src/net/tcpsock_posix.go:142 +0x28
net.(*TCPListener).Accept(0xc000290138)
	/usr/lib/golang/src/net/tcpsock.go:288 +0x3d
net/http.(*Server).Serve(0xc0003b8000, {0xd27ca0, 0xc000290138})
	/usr/lib/golang/src/net/http/server.go:3070 +0x385
net/http.(*Server).ListenAndServe(0xc0003b8000)
	/usr/lib/golang/src/net/http/server.go:2999 +0x7d
net/http.ListenAndServe(...)
	/usr/lib/golang/src/net/http/server.go:3255
github.com/guacsec/guac/cmd/graphql_playground/cmd.startServer()
	/home/jeffm/git/guac/cmd/graphql_playground/cmd/server.go:86 +0x9d0
github.com/guacsec/guac/cmd/graphql_playground/cmd.glob..func1(0x119f5c0?, {0xc00d89?, 0x0?, 0x0?})
	/home/jeffm/git/guac/cmd/graphql_playground/cmd/root.go:56 +0x113
github.com/spf13/cobra.(*Command).execute(0x119f5c0, {0xc000024240, 0x0, 0x0})
	/home/jeffm/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x119f5c0)
	/home/jeffm/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/jeffm/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/guacsec/guac/cmd/graphql_playground/cmd.Execute()
	/home/jeffm/git/guac/cmd/graphql_playground/cmd/root.go:118 +0x25
main.main()
	/home/jeffm/git/guac/cmd/graphql_playground/main.go:26 +0x17

goroutine 274592 [runnable]:
github.com/99designs/gqlgen/graphql.shouldIncludeNode({0x0, 0x0, 0x0?}, 0xc0026d1c50?)
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/executable_schema.go:135 +0x189
github.com/99designs/gqlgen/graphql.collectFields(0xc00271b320, {0xc005140980, 0x4, 0x0?}, {0x1194a20, 0x1, 0x1}, 0x0?)
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/executable_schema.go:32 +0x232
github.com/99designs/gqlgen/graphql.CollectFields(...)
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/executable_schema.go:23
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._OSVId(0xc0016871e0, {0xd28680, 0xc001e62870}, {0xc005140980, 0x4, 0x4}, 0xc004074cd0?)
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/osv.generated.go:327 +0x131
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext).marshalNOSVId2ᚖgithubᚗcomᚋguacsecᚋguacᚋpkgᚋassemblerᚋgraphqlᚋmodelᚐOSVId(0xbb3040?, {0xd28680?, 0xc001e62870?}, {0xc005140980?, 0x493c29?, 0x7f84b4130850?}, 0x58?)
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/osv.generated.go:472 +0xc5
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext).marshalNOSVId2ᚕᚖgithubᚗcomᚋguacsecᚋguacᚋpkgᚋassemblerᚋgraphqlᚋmodelᚐOSVIdᚄ.func1(0x0)
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/osv.generated.go:445 +0x107
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext).marshalNOSVId2ᚕᚖgithubᚗcomᚋguacsecᚋguacᚋpkgᚋassemblerᚋgraphqlᚋmodelᚐOSVIdᚄ(0xc0016871e0, {0xd28680, 0xc001e62840}, {0xc005140980, 0x4, 0x4}, {0xc005756868, 0x1, 0x1})
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/osv.generated.go:448 +0x30e
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._OSV_osvIds(0xc0016871e0, {0xd28680, 0xc001e627e0}, {0xc00423c300?, {0xc005140980?, 0x3?, 0x3?}}, 0xc001e62720)
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/osv.generated.go:103 +0x2f0
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._OSV(0xc0016871e0, {0xd28680, 0xc001e627e0}, {0xc0036ee9c0, 0x2, 0x2}, 0xc001e627e0?)
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/osv.generated.go:308 +0x3e8
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext).marshalNOSV2ᚖgithubᚗcomᚋguacsecᚋguacᚋpkgᚋassemblerᚋgraphqlᚋmodelᚐOsv(0xd28680?, {0xd28680?, 0xc001e627e0?}, {0xc0036ee9c0?, 0xc0036ee9c0?, 0x60?}, 0x6?)
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/osv.generated.go:418 +0xc5
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._IsVulnerability_osv(0xc0016871e0, {0xd28680, 0xc001e626f0}, {0xc00423c800?, {0xc0036ee9c0?, 0x2?, 0x2?}}, 0xc0036f2b40)
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/isVulnerability.generated.go:103 +0x288
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._IsVulnerability(0xc0016871e0, {0xd28680, 0xc001e626f0}, {0xc0016875f0, 0x1, 0x1}, 0xc001e626f0?)
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/isVulnerability.generated.go:539 +0x3e6
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext).marshalNIsVulnerability2ᚖgithubᚗcomᚋguacsecᚋguacᚋpkgᚋassemblerᚋgraphqlᚋmodelᚐIsVulnerability(0xd28680?, {0xd28680?, 0xc001e626f0?}, {0xc0016875f0?, 0xc0016875f0?, 0x203000?}, 0xc004075408?)
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/isVulnerability.generated.go:657 +0xc5
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Mutation_ingestIsVulnerability(0xc0016871e0, {0xd28680, 0xc001e62420}, {0xc00423c180?, {0xc0016875f0?, 0xd28680?, 0xc004075470?}})
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/artifact.generated.go:2205 +0x299
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Mutation.func17({0xd28680?, 0xc001e62420?})
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/artifact.generated.go:4351 +0x45
github.com/99designs/gqlgen/graphql/executor.processExtensions.func3({0xd28680?, 0xc001e62420?}, 0xb00d40?)
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/executor/extensions.go:69 +0x26
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executionContext)._Mutation(0xc0016871e0, {0xd28680, 0xc0026d1d70}, {0xc0033760c0, 0x3, 0x4})
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/artifact.generated.go:4350 +0x1f44
github.com/guacsec/guac/pkg/assembler/graphql/generated.(*executableSchema).Exec.func2({0xd28680?, 0xc0026d1d40?})
	/home/jeffm/git/guac/pkg/assembler/graphql/generated/root_.generated.go:1920 +0x93
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1.1({0xd28680, 0xc0026d1d40})
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/executor/executor.go:119 +0x2b
github.com/99designs/gqlgen/graphql/executor.processExtensions.func2({0xd28680?, 0xc0026d1d40?}, 0xb00d40?)
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/executor/extensions.go:66 +0x26
github.com/99designs/gqlgen/graphql/executor.(*Executor).DispatchOperation.func1.1({0xd28680, 0xc0026d1c80})
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/executor/executor.go:118 +0x113
github.com/99designs/gqlgen/graphql/handler/transport.POST.Do({}, {0xd27eb0?, 0xc0007e0620}, 0xc0036d7a00, {0xd26f20, 0xc0002d1900})
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/handler/transport/http_post.go:87 +0x59f
github.com/99designs/gqlgen/graphql/handler.(*Server).ServeHTTP(0xc0002ad4a0, {0xd27eb0, 0xc0007e0620}, 0xc0036d7a00)
	/home/jeffm/go/pkg/mod/github.com/99designs/gqlgen@v0.17.27/graphql/handler/server.go:121 +0x212
net/http.(*ServeMux).ServeHTTP(0x0?, {0xd27eb0, 0xc0007e0620}, 0xc0036d7900)
	/usr/lib/golang/src/net/http/server.go:2487 +0x149
net/http.serverHandler.ServeHTTP({0xd25c78?}, {0xd27eb0, 0xc0007e0620}, 0xc0036d7900)
	/usr/lib/golang/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0002d0140, {0xd28680, 0xc0003b62d0})
	/usr/lib/golang/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:3102 +0x4db

goroutine 273807 [runnable]:
net/http.(*connReader).startBackgroundRead.func2()
	/usr/lib/golang/src/net/http/server.go:674
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/golang/src/net/http/server.go:674 +0xca

goroutine 274652 [IO wait]:
internal/poll.runtime_pollWait(0x7f84b53dc8e8, 0x72)
	/usr/lib/golang/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc003ae1e00?, 0xc00352c311?, 0x0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc003ae1e00, {0xc00352c311, 0x1, 0x1})
	/usr/lib/golang/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc003ae1e00, {0xc00352c311?, 0xc003f79a98?, 0xc000720768?})
	/usr/lib/golang/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc002e2a540, {0xc00352c311?, 0xc004d4b9f0?, 0xd28680?})
	/usr/lib/golang/src/net/net.go:183 +0x45
net/http.(*connReader).backgroundRead(0xc00352c300)
	/usr/lib/golang/src/net/http/server.go:678 +0x3f
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/golang/src/net/http/server.go:674 +0xca
exit status 2
```

</details>

### PR DESCRIPTION
**Pull request by jeffmendoza**
Fixes #672

### CODE REVIEW

**Review by mihaimaruseac — COMMENTED** [review]
I think it's better to grab it only in `buildModelNodes` and `neighbordFromId` (read only in both)

**Comment by lumjjb** [comment]
hmm wouldn't you be releasing the lock betweeen them though - which may cause a change of state?

**Comment by mihaimaruseac** [comment]
I think it's a balance between having the lock taken for too long (so slowing down future ingestion which needs to write and wait for all readers to stop) and having incomplete path results (we might miss a neighbor that got added in between two locks but this is equivalent to running the entire path query before ingesting that neighbor).

**Comment by lumjjb** [comment]
hmm ok, seems like there are no pathological cases in this case and the result will only be strictly better than if the lock was taken only at the start. Thus should be a net positive in all cases, so agreed.

**Comment by jeffmendoza** [comment]
I was thinking it would be better to handle all the locking in the top-level functions that serve the graphql queries throughout the backend. In that case, you don't need to think about locking when working in a helper or smaller function. Some functions are called by multiple top level functions, and it would be complicated to always consider whether to lock or not.

Agree it should be fine to release and re-grab the lock in between, ex:

```go
func (c *demoClient) Neighbors(ctx context.Context, source string) ([]model.Node, error) {
	id, err := strconv.ParseUint(source, 10, 32)
	if err != nil {
		return nil, err
	}

	c.m.RLock()
	neighbors, err := c.neighborsFromId(uint32(id))
	if err != nil {
		c.m.RUnlock()
		return nil, err
	}
	c.m.RUnlock()

	c.m.RLock()
	defer c.m.RUnlock()
	return c.buildModelNodes(neighbors)
}
```
??

**Comment by mihaimaruseac** [comment]
Ok, let's lock only on top level functions as that makes sure we won't accidentally call functions that expect locking without doing so.

**Comment by jeffmendoza** [comment]
SG
updated

**Review by mihaimaruseac — APPROVED** [review]

**Pull request merged**
