### PR TITLE
Clean up docs and remove old SETUP.md

### PR DESCRIPTION
**Pull request by lumjjb**

### CODE REVIEW

**Comment by jeffmendoza** [comment]
Need to update e2e: https://github.com/guacsec/guac/blob/260dd42d728d4ba7f3f92ea509261cbc45291a71/internal/testing/e2e/e2e#L45
https://github.com/guacsec/guac/blob/260dd42d728d4ba7f3f92ea509261cbc45291a71/internal/testing/e2e/e2e#L82

**Comment by lumjjb** [comment]
Thanks for the pointer! Just pushed the recommended changes!

**Review by mihaimaruseac — COMMENTED** [review]
Looks good, but I think we still have some references to SETUP.md in CONTRIBUTING.md

**Review by jeffmendoza — APPROVED** [review]
Looks good for now. We will need to do a top-down review of the docs:

- what goes in this repo vs the website
- what is the order of a top-level table of contents
- what we point people to first.
- etc.

**Pull request merged**
