### PR TITLE
Update packages for slices import

### PR DESCRIPTION
**Pull request by naveensrinivasan**
# Description of the PR
- Replace `golang.org/x/exp/slices` with `slices` import
- Fix https://github.com/guacsec/guac/issues/1350

# PR Checklist

- [x] All commits have [a Developer Certificate of Origin (DCO)](https://wiki.linuxfoundation.org/dco) -- they are generated using `-s` flag to `git commit`.
- [ ] All new changes are covered by tests
- [ ] If GraphQL schema is changed, `make generate` has been run
- [ ] If `collectsub` protobuf has been changed, `make proto` has been run
- [ ] All CI checks are passing (tests and formatting)
- [ ] All dependent PRs have already been merged

### CODE REVIEW

**Review by mihaimaruseac — CHANGES_REQUESTED** [review]
This is just syntactic replace, but does not take into account that the API of the two packages is different.

See the following from the linked issue:

>  `slices` uses comparison functions that return integers, while (the version used of) `golang.org/x/exp/slices` uses comparison functions that return booleans. The comparison functions in roughly [these](https://github.com/search?q=repo%3Aguacsec%2Fguac+%2Fslices.*Func%2F&type=code) places would need to be updated.

**Comment by naveensrinivasan** [comment]
> This is just syntactic replace, but does not take into account that the API of the two packages is different.
> 
> See the following from the linked issue:
> 
> > `slices` uses comparison functions that return integers, while (the version used of) `golang.org/x/exp/slices` uses comparison functions that return booleans. The comparison functions in roughly [these](https://github.com/search?q=repo%3Aguacsec%2Fguac+%2Fslices.*Func%2F&type=code) places would need to be updated.

I agree. Thanks.

If I am not wrong, only these must be addressed `sort.SliceStable`.  

Let me now.

**Comment by jeffmendoza** [comment]
I changed a bunch of the compare funcs from `bool` to `int` in #1352

**Review by mihaimaruseac — APPROVED** [review]
In that case, approving, as I see the CI passed. But it doesn't harm to do an actual check and make sure the new API works as intended.

**Review by jeffmendoza — APPROVED** [review]

**Pull request merged**
