### PR TITLE
Add a website

### PR DESCRIPTION
**Pull request by rgreinho**
Adds a presentation website containing the information required for
people to understand what GUAC is as well as the guidelines to get new
contributors onboarded.

Signed-off-by: Rémy Greinhofer <remy.greinhofer@gmail.com>

### CODE REVIEW

**Comment by lumjjb** [comment]
Awesome - would it be easy to have the site code be part of another repository and then pull the info from this repo in the docs folder?

**Comment by mihaimaruseac** [comment]
I think it will go in the github pages branch so it will show up at something like `guac.github.io`

**Comment by rgreinho** [comment]
No, that would make it more complicated. Once we agree on the site (i.e. theme, colors, fonts, logos), I'll set up the github action to publish it automatically on github pages.

**Comment by lumjjb** [comment]
hmm, should this be open against a new website branch?

**Comment by rgreinho** [comment]
Nope. The generated content will be put there automatically via the GitHub action.

**Review by pxp928 — APPROVED** [review]
LGTM. We might have to make some tweaks once the website is up.

**Review by lumjjb — CHANGES_REQUESTED** [review]
i'm still skeptical of having non-guac code in the main branch of the repo, it doesn't have clear separation.

**Pull request closed without merging**
