### PR TITLE
feat: implement cyclonedx processor

### PR DESCRIPTION
**Pull request by cpendery**
## 📝 Description
Implements a CycloneDX Processor. Adding support for a guesser & XML format guesser in a separate PR

https://github.com/guacsec/guac/issues/102

### CODE REVIEW

**Review by lumjjb — APPROVED** [review]
lgtm, want to take it out of draft?

**Comment by pxp928** [comment]
Looks good but doesn't the guesser & XML format guesser a pre-req for this PR?

**Comment by cpendery** [comment]
@lumjjb Should I close this in lieu of https://github.com/guacsec/guac/pull/140?

**Comment by lumjjb** [comment]
@cpendery i'd like to have the XML portions be integrated into that once #140 is merged... so don't throw away this code - it's going to be useful still for XML! But yea once that PR is open we'll close up this one

**Comment by cpendery** [comment]
> @cpendery i'd like to have the XML portions be integrated into that once #140 is merged... so don't throw away this code - it's going to be useful still for XML! But yea once that PR is open we'll close up this one

Sounds good, I can add the xml support as soon as https://github.com/guacsec/guac/pull/140 gets merged. I fixed the xml guesser PR which should be ready for review. Thanks @lumjjb

**Pull request closed without merging**
