### PR TITLE
Remove guacone graphql. Rename playground to guac.

### PR DESCRIPTION
**Pull request by jeffmendoza**
First todo item on #719 

Also removes neo4j args from guacone, some commands were including those in args for some reason. Neo4j args should only be in the `guac` command from now on.

### CODE REVIEW

**Comment by jeffmendoza** [comment]
Note: keeping the arg names from `guacone graphql` over the ones from `graphql_playground`

**Comment by lumjjb** [comment]
oh i see... you're taking it out, i was confused with the naming

**Comment by lumjjb** [comment]
Can we rename it to `guac-gql` binary? I think we'd want to ensure that the messaging is that GUAC is a framework and the ingestion pipeline is part of what's in that box which makes the magic work, and not something that we want people to be building into the ingestion API.

**Comment by pxp928** [comment]
+1 this would be more clear.

**Comment by jeffmendoza** [comment]
`guac` -> `guacgql` done.

**Review by pxp928 — APPROVED** [review]
LGTM

**Pull request merged**
