### PR TITLE
Consolidate duplicate flag declarations

### PR DESCRIPTION
**Pull request by lukehinds**
A bit of uneeded DRY. Both commands share the same set of flags so consolidate into the root init. If individual flags are ever needed, we can set them in the init of each cmd.

Signed-off-by: Luke Hinds <lhinds@redhat.com>

### CODE REVIEW

**Review by lumjjb — APPROVED** [review]
🎉 Thanks Luke!! :) LGTM

**Comment by lukehinds** [comment]
Not sure why DCO bot is unhappy, I signed my commit.

**Comment by lumjjb** [comment]
Hmm.. I think the 2nd commit isn't signed (just trying to look at it from
my phone so not looking at git output)

**Comment by lukehinds** [comment]
> Hmm.. I think the 2nd commit isn't signed (just trying to look at it from my phone so not looking at git output)

oh yes, that sounds right. I think if you click on 'Details' you can set it to pass, as the bot is not very smart to pick up a change, even if I did `--amend`

**Review by mihaimaruseac — APPROVED** [review]

**Comment by mihaimaruseac** [comment]
Hmm, can you force push the amended commit? I think that solved the issue for me last time I forgot to pass the signoff flag.

I'll let @lumjjb do the set-it-to-pass-from-details step alternative.

**Comment by lumjjb** [comment]
i manually made the DCO bot pass , but the @kodiakhq bot seems to not want to pick it up - can you force push again to try and trigger it?

**Comment by lukehinds** [comment]
`git commit --amend --force` seems to have done the job.

**Pull request merged**
