### PR TITLE
Don't persist credentials in actions/checkout

### LINKED ISSUE #2267: zizmor audit for CI workflow
```
🌈 completed ci.yaml
warning[artipacked]: credential persistence through GitHub Actions artifacts
  --> .github/workflows/ci.yaml:69:9
   |
69 |         - name: Checkout code
   |  _________-
70 | |         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v3
   | |________________________________________________________________________________- does not set persist-credentials: false
   |
   = note: audit confidence → Low

warning[artipacked]: credential persistence through GitHub Actions artifacts
   --> .github/workflows/ci.yaml:108:9
    |
108 |         - name: Checkout code
    |  _________-
109 | |         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v3
    | |________________________________________________________________________________- does not set persist-credentials: false
    |
    = note: audit confidence → Low

warning[artipacked]: credential persistence through GitHub Actions artifacts
   --> .github/workflows/ci.yaml:146:7
    |
146 |     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    |       --------------------------------------------------------------- does not set persist-credentials: false
    |
    = note: audit confidence → Low

warning[artipacked]: credential persistence through GitHub Actions artifacts
  --> .github/workflows/ci.yaml:38:9
   |
38 |         - name: Checkout code
   |  _________-
39 | |         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v3
   | |________________________________________________________________________________- does not set persist-credentials: false
   |
   = note: audit confidence → Low

warning[artipacked]: credential persistence through GitHub Actions artifacts
  --> .github/workflows/ci.yaml:90:9
   |
90 |         - name: Checkout code
   |  _________-
91 | |         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v3
   | |________________________________________________________________________________- does not set persist-credentials: false
   |
   = note: audit confidence → Low

warning[artipacked]: credential persistence through GitHub Actions artifacts
   --> .github/workflows/ci.yaml:225:9
    |
225 |         - name: Checkout code
    |  _________-
226 | |         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v3
    | |________________________________________________________________________________- does not set persist-credentials: false
    |
    = note: audit confidence → Low

6 findings (0 ignored): 0 unknown, 0 informational, 0 low, 6 medium, 0 high
```

### PR DESCRIPTION
**Pull request by funnelfiasco**
Fixes #2267

# PR Checklist

- [x] All commits have [a Developer Certificate of Origin (DCO)](https://wiki.linuxfoundation.org/dco) -- they are generated using `-s` flag to `git commit`.
- [ ] All new changes are covered by tests
- [ ] If GraphQL schema is changed, `make generate` has been run
- [ ] If GraphQL schema is changed, GraphQL client updates/additions have been made
- [ ] If OpenAPI spec is changed, `make generate` has been run
- [ ] If ent schema is changed, `make generate` has been run
- [ ] If `collectsub` protobuf has been changed, `make proto` has been run
- [ ] All CI checks are passing (tests and formatting)
- [ ] All dependent PRs have already been merged

### CODE REVIEW

**Review by pxp928 — APPROVED** [review]

**Comment by funnelfiasco** [comment]
Failure of "ci/CI for unit tests" failure doesn't appear to be related to this change.

**Comment by funnelfiasco** [comment]
Integration test failure is due to HTTP 502 received from ClearlyDefined

**Comment by pxp928** [comment]
made a bug report here: https://github.com/guacsec/guac/issues/2273

**Review by mihaimaruseac — APPROVED** [review]

**Comment by lumjjb** [comment]
rebased so the CI will pass

**Pull request merged**
