### PR TITLE
Fixed the nil error in SLSA Parser

### PR DESCRIPTION
**Pull request by naveensrinivasan**
# Description of the PR

- Improve error messages for the `Parse` function
- Add a check for a `nil` document

# PR Checklist

- [x] All commits have [a Developer Certificate of Origin (DCO)](https://wiki.linuxfoundation.org/dco) -- they are generated using `-s` flag to `git commit`.
- [x] All new changes are covered by tests
- [ ] If GraphQL schema is changed, `make generate` has been run
- [ ] If `collectsub` protobuf has been changed, `make proto` has been run
- [ ] All CI checks are passing (tests and formatting)
- [ ] All dependent PRs have already been merged

### CODE REVIEW

**Review by mihaimaruseac — COMMENTED** [review]
Is there a scenario where we'd have the doc be `nil`?

**Comment by naveensrinivasan** [comment]
> Is there a scenario where we'd have the doc be `nil`?

Maybe not. I was using the func and realized that it could be nil.

**Comment by mihaimaruseac** [comment]
It doesn't make sense to add a check for something that we know can never be false.

**Comment by naveensrinivasan** [comment]
> It doesn't make sense to add a check for something that we know can never be false.

OK. I'll close it.

**Pull request closed without merging**
