### PR TITLE
graphql doc review

### PR DESCRIPTION
**Pull request by lumjjb**
Ran through the demos! looks good! Some cleanup and added some notes on difficulties i've had. 

CC: @jeffmendoza

### CODE REVIEW

**Review by jeffmendoza — APPROVED** [review]
Looks good. Personally I don't like make for the demo. It's opaque to the user what is going on, and one would assume it is something more complex than what it is. We are just running `go build`. In this case, instead of `go run` we could do `go install ./cmd/...` and then have folks run the commands.

I agree with a `Makefile` for the purposes of having all the devs using the same workflow, and for generating releases with the appropriate flags, but not for the demo. Same thing for the `docker build` and `compose up` in the compose tutorial.

**Comment by lumjjb** [comment]
i lean towards using `make` since it allows the docs to keep a bit more in sync with development, and allows us to correct under the hood without making running the command overly complicated (e.g. if we need extra compilation flags). Since this is a preference, maybe let's get some fuzzy consensus

@mlieberman85 @pxp928 @SantiagoTorres @mihaimaruseac

**Comment by SantiagoTorres** [comment]
+1 on make,  we can perhaps add a target (e.g., test) to spin up the try guacone w/ in-memory backend bits as described in the PR

**Comment by mihaimaruseac** [comment]
I'm also +1 on solution that makes docs stay up to date regardless of how we update the steps. This seems to be `make` now.

**Review by pxp928 — APPROVED** [review]

**Comment by pxp928** [comment]
@lumjjb this can be rebased to fix the CI issues

**Review by SantiagoTorres — APPROVED** [review]
LGTM!

**Pull request merged**
