### PR TITLE
refactor ingestor in preparation for pluggability

### PR DESCRIPTION
**Pull request by lumjjb**
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

### CODE REVIEW

**Comment by mlieberman85** [comment]
Can you elaborate in the PR/commit notes about the pluggability? Based on previous discussions it seems like we want to take a different approach for pluggability here compared to the collectors.

The predicate dictionary sounded like it would be a separate component that would live elsewhere with some schema to help us map from predicate -> nodes/edges?

Do we plan to have something like a `PredicateDictionaryParser` that will call out to an external predicate dictionary for most/all ite6 predicates?

**Review by pxp928 — COMMENTED** [review]
This looks good. My only comment is should the file be called `common.go`? or would it be similar to like the processor and collector where the SPDX `graphbuilder` will be different compared to the SLSA one.

**Comment by pxp928** [comment]
We should also break them out into different packages to be consistent with the others

**Comment by lumjjb** [comment]
updated!

**Review by pxp928 — APPROVED** [review]
LGTM

**Review by mihaimaruseac — APPROVED** [review]
LGTM, but I think in general we'd like to have predicate dictionaries build a subset of the graph and as we traverse the document(s) (tree) we keep extending the graph with only what the predicate says at the time (as I'm thinking we might get too many spurious edges if we'll be going with this approach in the long term). But maybe this would be for a later time.

**Pull request merged**
