### PR TITLE
Fixed parsing when bom contains no dependent components

### PR DESCRIPTION
**Pull request by knrc**

### CODE REVIEW

**Comment by pxp928** [comment]
@lumjjb @mlieberman85 Should this merge into [heuristic-dev](https://github.com/guacsec/guac/tree/heuristic-dev)? Also, FYI @kevinconner there is a [heuristic-dev](https://github.com/guacsec/guac/tree/heuristic-dev) where we are trying to capture all the changes we need to make for SBOM parsing.

**Comment by lumjjb** [comment]
Thanks @knrc for catching this!

I think this would work for the branch but also should be good with merging into main since it is not changing any behavior that is used in SETUP.md, so its not intrusive on the current work we're doing in that sense.

**Review by pxp928 — APPROVED** [review]
LGTM! Thanks @knrc

**Comment by knrc** [comment]
@pxp928 Good to know about [heuristic-dev](https://github.com/guacsec/guac/tree/heuristic-dev), I'll take a look later today and see what is going on in that branch.

**Review by lumjjb — APPROVED** [review]
Thanks @knrc !

**Pull request merged**
