### PR TITLE
added inmemory key provider

### LINKED ISSUE #77: task: [ingestor] create inmemory key provider for ingestor
inmemory key provider is an implementation of the key interface. This will store keys in-memeory

### PR DESCRIPTION
**Pull request by pxp928**
Signed-off-by: pxp928 <parth.psu@gmail.com>

in-memory key provider that implements the key interface.

Closes #77

### CODE REVIEW

**Comment by mlieberman85** [comment]
I can't remember if we had the conversation about whether or not the keyprovider should hold onto the wrapped key. Did we have a decision on that?

**Comment by pxp928** [comment]
> I can't remember if we had the conversation about whether or not the keyprovider should hold onto the wrapped key. Did we have a decision on that?

Currently we create the wrapped key during the retrieval from the provider. What would be the use case to store them?

**Comment by pxp928** [comment]
Changed to store wrapped Key directly into the key provider.

**Review by lumjjb — APPROVED** [review]
lgtm

**Review by mlieberman85 — APPROVED** [review]
LGTM

**Pull request merged**
