### PR TITLE
Fix typo in osv.PRODUCER_ID

### PR DESCRIPTION
**Pull request by pombredanne**
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Review by mihaimaruseac — APPROVED** [review]

**Review by lumjjb — DISMISSED** [review]
lgtm

**Comment by lumjjb** [comment]
looks like the test had the typo as well!

**Review by pxp928 — COMMENTED** [review]
`"producer_id":"guecsec/guac"` in osv_test.go on line 45, 76, 107 and 156 also has the same typo. Once that is fixed the CI will pass. Thanks!

**Comment by lumjjb** [comment]
i pushed a commit to fix to test , PTAL @pxp928

**Review by pxp928 — APPROVED** [review]

**Pull request merged**
