### PR TITLE
[fix] ingests nouns before verbs for test data

### PR DESCRIPTION
**Pull request by stevemenezes**
# Description of the PR

Address issue https://github.com/guacsec/guac/issues/1000

# PR Checklist

- [x] All commits have [a Developer Certificate of Origin (DCO)](https://wiki.linuxfoundation.org/dco) -- they are generated using `-s` flag to `git commit`.
- [ ] All new changes are covered by tests
- [ ] If GraphQL schema is changed, `make generate` has been run
- [ ] If `collectsub` protobuf has been changed, `make proto` has been run
- [ ] All CI checks are passing (tests and formatting)
- [ ] All dependent PRs have already been merged

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
In principle looks good, but need to sign CLA

**Comment by stevemenezes** [comment]
Hey @mihaimaruseac sure thing, will check with the team internally and see whether we have a corporate CLA or not. For this PR looks like I need to sign an individual CLA since my personal email associated with the commit.

**Review by lumjjb — APPROVED** [review]
LGTM! Thanks @stevemenezes ! This should merge after CLA check is good!

**Comment by stevemenezes** [comment]
@lumjjb @mihaimaruseac on chatting with the team internally they recommended that I make use of the company CLA. Might have to open another PR using the corporate email, will keep y'all posted for reviews once done!

**Review by pxp928 — APPROVED** [review]
LGTM! Thanks @stevemenezes

**Pull request merged**
