### PR TITLE
Add scorecard guesser/processor

### PR DESCRIPTION
**Pull request by lumjjb**
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

### CODE REVIEW

**Comment by lumjjb** [comment]
@azeemshaikh38 @naveensrinivasan FYI

**Comment by azeemshaikh38** [comment]
> @azeemshaikh38 @naveensrinivasan FYI

Exciting! 

Note that, we don't officially support Scorecard as a library since there are limited usecases for that. Would suggest subscribing to g/ossf-scorecard-dev and g/ossf-scorecard-announce in case there are breaking changes that might affect this.

**Review by pxp928 — APPROVED** [review]
LGTM

**Comment by lumjjb** [comment]
rebased

**Review by mlieberman85 — APPROVED** [review]
LGTM

**Pull request merged**
