### PR TITLE
Updates ingesting data commands

### PR DESCRIPTION
**Pull request by rewanthtammana**
Signed-off-by: Rewanth Tammana <22347290+rewanthtammana@users.noreply.github.com>

### Description

The mentioned flags doesn't seem to exist anymore. I updated the docs with a working command.

### CODE REVIEW

**Review by pxp928 — APPROVED** [review]
Thanks @rewanthtammana!

**Comment by rewanthtammana** [comment]
Closing the PR. I was working on the outdated code. I compiled the binaries again, then pulled the code from main branch but forgot to build the binaries after pull.

**Comment by pxp928** [comment]
oops good catch that was the old code.

**Comment by rewanthtammana** [comment]
@pxp928 Hehe.. thanks 😁 I should've been more cautious.

**Pull request closed without merging**
